create table public.videos
(
    id            bigint generated by default as identity
        primary key,
    content_type  varchar(255),
    data          oid,
    name          varchar(255),
    preview_photo oid
);

alter table public.videos
    owner to postgres;

