create table public.users
(
    id            bigint generated by default as identity
        primary key,
    username  varchar(255),
    email          varchar(255),
    password varchar(255)
);

alter table public.users
    owner to postgres;

